# Generated by Django 3.1.3 on 2020-11-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(max_length=30)),
                ('node_key', models.UUIDField()),
                ('node_id', models.UUIDField()),
            ],
            options={
                'ordering': ['node_id'],
            },
        ),
    ]
